import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import Header from '@/components/header';
import Footer from '@/components/footer';
import { ThemeProvider } from '@/components/theme-provider';
import { ChatbotProvider } from '@/components/chatbot-context'; // Import ChatbotProvider

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: 'hsl(60 9.1% 97.8%)', // change this value (you can get it from your css variables, make sure to include 'hsl' and commas)
        },
      }}
    >
      <html
        lang='en'
        className='scroll-smooth antialiased'
        suppressHydrationWarning
      >
        <body className={`flex min-h-screen flex-col ${inter.className}`}>
          <ThemeProvider>
            <ChatbotProvider> {/* Wrap with ChatbotProvider */}
              <Header />
              <main className='grow'>{children}</main>
              <Footer />
            </ChatbotProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}